ProjetoBandtec/Controllers/CRUDController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ProjetoBandtec.Models;

namespace ProjetoBandtec.Controllers
{
    public class CRUDController : Controller
    {
        private ModeloDeDados db = new ModeloDeDados();

        // GET: CRUD
        public ActionResult Index()
        {
            var xptotba02_analista = db.xptotba02_analista.Include(x => x.xptotba01_cliente);
            return View(xptotba02_analista.ToList());
        }

        // GET: CRUD/Details/5
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            xptotba02_analista xptotba02_analista = db.xptotba02_analista.Find(id);
            if (xptotba02_analista == null)
            {
                return HttpNotFound();
            }
            return View(xptotba02_analista);
        }

        // GET: CRUD/Create
        public ActionResult AdicionarAnalista()
        {
            ViewBag.cliente_hostname = new SelectList(db.xptotba01_cliente, "hostname", "cnpj");
            return View();
        }

        // POST: CRUD/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdicionarAnalista([Bind(Include = "id,nome_usuario,senha,tipo_usuario,cliente_hostname")] xptotba02_analista xptotba02_analista)
        {
            if (ModelState.IsValid)
            {
                db.xptotba02_analista.Add(xptotba02_analista);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.cliente_hostname = new SelectList(db.xptotba01_cliente, "hostname", "cnpj", xptotba02_analista.cliente_hostname);
            return View(xptotba02_analista);
        }

        // GET: CRUD/Edit/5
        public ActionResult EditarAnalista(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            xptotba02_analista xptotba02_analista = db.xptotba02_analista.Find(id);
            if (xptotba02_analista == null)
            {
                return HttpNotFound();
            }
            ViewBag.cliente_hostname = new SelectList(db.xptotba01_cliente, "hostname", "cnpj", xptotba02_analista.cliente_hostname);
            return View(xptotba02_analista);
        }

        // POST: CRUD/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarAnalista([Bind(Include = "id,nome_usuario,senha,tipo_usuario,cliente_hostname")] xptotba02_analista xptotba02_analista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(xptotba02_analista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cliente_hostname = new SelectList(db.xptotba01_cliente, "hostname", "cnpj", xptotba02_analista.cliente_hostname);
            return View(xptotba02_analista);
        }

        // GET: CRUD/Delete/5
        public ActionResult DeletarAnalista(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            xptotba02_analista xptotba02_analista = db.xptotba02_analista.Find(id);
            if (xptotba02_analista == null)
            {
                return HttpNotFound();
            }
            return View(xptotba02_analista);
        }

        // POST: CRUD/Delete/5
        [HttpPost, ActionName("DeletarAnalista")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            xptotba02_analista xptotba02_analista = db.xptotba02_analista.Find(id);
            db.xptotba02_analista.Remove(xptotba02_analista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoBandtec/Views/_Layouts/LayoutCRUD.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Site XPTO</title>
    <link href="~/Content/CSS/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/CSS/CRUD.css" rel="stylesheet" />
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <header>
        <nav>
            <a title="Tela de Máquinas" href=@Url.Action("Home", "XPTO")>Home</a>
            <a title="Baixe o nosso aplicativo" href=@Url.Action("Download", "XPTO")>Download</a>
            <a class="bloco_nav" href=@Url.Action("Index", "CRUD")>Analistas</a>
        </nav>
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <div class="logo_login">
        <img alt="Logo da Empresa XPTO" src="@Url.Content("~/Content/images/logoprovisorio.png")" />
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ProjetoBandtec/Views/_Layouts/LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="@Url.Content("~/Content/CSS")" /> @RenderSection("css", required: false)
</head>

<body>
    @RenderBody();
    <script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script> @RenderSection("script", required: false)
</body>
 
</html>

ProjetoBandtec/Views/_Layouts/LayoutSite.cshtml
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="@Url.Content("~/Content/CSS")" /> @RenderSection("css", required: false)
</head>

<body>
    @RenderBody()
    <script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script> @RenderSection("script", required: false)
</body>
</html>